[profile.default]
    src = 'src/contracts'
    test = 'test'
    out = 'out'
    libs = ['node_modules', 'lib']

    solc = "0.8.19"
    ffi = true
    optimizer = false
    optimizer_runs = 200

# See more config options https://github.com/gakonst/foundry/tree/master/config